version: "3"

services:
  symfony_php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    environment:
      DATABASE_URL: mysql://${DOCKER_DB_USER}:${DOCKER_DB_PASSWORD}@db:3306/${DOCKER_DB_NAME}
      JWT_SECRET_KEY: /var/www/symfony/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/symfony/config/jwt/public.pem
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      CORS_ALLOW_ORIGIN: '*'

  db:
    image: mysql:latest
    container_name: symfony_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
